from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

netlistscript = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'BarrelJack', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BarrelJack'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_BarrelJack:BarrelJack_Wuerth_694106301002_Horizontal', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='GND2',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_1206_3216Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'KSZ9477S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'KSZ9477S'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'QFP40P1600X1600X120-129N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.BIDIR),
            Pin(num='2',name='P2',func=pin_types.BIDIR),
            Pin(num='3',name='P3',func=pin_types.BIDIR),
            Pin(num='4',name='P4',func=pin_types.BIDIR),
            Pin(num='5',name='P5',func=pin_types.BIDIR),
            Pin(num='6',name='P6',func=pin_types.BIDIR),
            Pin(num='7',name='P7',func=pin_types.BIDIR),
            Pin(num='8',name='P8',func=pin_types.BIDIR),
            Pin(num='9',name='P9',func=pin_types.BIDIR),
            Pin(num='10',name='P10',func=pin_types.BIDIR),
            Pin(num='11',name='P11',func=pin_types.BIDIR),
            Pin(num='12',name='P12',func=pin_types.BIDIR),
            Pin(num='13',name='P13',func=pin_types.BIDIR),
            Pin(num='14',name='P14',func=pin_types.BIDIR),
            Pin(num='15',name='P15',func=pin_types.BIDIR),
            Pin(num='16',name='P16',func=pin_types.BIDIR),
            Pin(num='17',name='P17',func=pin_types.BIDIR),
            Pin(num='18',name='P18',func=pin_types.BIDIR),
            Pin(num='19',name='P19',func=pin_types.BIDIR),
            Pin(num='20',name='P20',func=pin_types.BIDIR),
            Pin(num='21',name='P21',func=pin_types.BIDIR),
            Pin(num='22',name='P22',func=pin_types.BIDIR),
            Pin(num='23',name='P23',func=pin_types.BIDIR),
            Pin(num='24',name='P24',func=pin_types.BIDIR),
            Pin(num='25',name='P25',func=pin_types.BIDIR),
            Pin(num='26',name='P26',func=pin_types.BIDIR),
            Pin(num='27',name='P27',func=pin_types.BIDIR),
            Pin(num='28',name='P28',func=pin_types.BIDIR),
            Pin(num='29',name='P29',func=pin_types.BIDIR),
            Pin(num='30',name='P30',func=pin_types.BIDIR),
            Pin(num='31',name='P31',func=pin_types.BIDIR),
            Pin(num='32',name='P32',func=pin_types.BIDIR),
            Pin(num='33',name='P33',func=pin_types.BIDIR),
            Pin(num='34',name='P34',func=pin_types.BIDIR),
            Pin(num='35',name='P35',func=pin_types.BIDIR),
            Pin(num='36',name='P36',func=pin_types.BIDIR),
            Pin(num='37',name='P37',func=pin_types.BIDIR),
            Pin(num='38',name='P38',func=pin_types.BIDIR),
            Pin(num='39',name='P39',func=pin_types.BIDIR),
            Pin(num='40',name='P40',func=pin_types.BIDIR),
            Pin(num='41',name='P41',func=pin_types.BIDIR),
            Pin(num='42',name='P42',func=pin_types.BIDIR),
            Pin(num='43',name='P43',func=pin_types.BIDIR),
            Pin(num='44',name='P44',func=pin_types.BIDIR),
            Pin(num='45',name='P45',func=pin_types.BIDIR),
            Pin(num='46',name='P46',func=pin_types.BIDIR),
            Pin(num='47',name='P47',func=pin_types.BIDIR),
            Pin(num='48',name='P48',func=pin_types.BIDIR),
            Pin(num='49',name='P49',func=pin_types.BIDIR),
            Pin(num='50',name='P50',func=pin_types.BIDIR),
            Pin(num='51',name='P51',func=pin_types.BIDIR),
            Pin(num='52',name='P52',func=pin_types.BIDIR),
            Pin(num='53',name='P53',func=pin_types.BIDIR),
            Pin(num='54',name='P54',func=pin_types.BIDIR),
            Pin(num='55',name='P55',func=pin_types.BIDIR),
            Pin(num='56',name='P56',func=pin_types.BIDIR),
            Pin(num='57',name='P57',func=pin_types.BIDIR),
            Pin(num='58',name='P58',func=pin_types.BIDIR),
            Pin(num='59',name='P59',func=pin_types.BIDIR),
            Pin(num='60',name='P60',func=pin_types.BIDIR),
            Pin(num='61',name='P61',func=pin_types.BIDIR),
            Pin(num='62',name='P62',func=pin_types.BIDIR),
            Pin(num='63',name='P63',func=pin_types.BIDIR),
            Pin(num='64',name='P64',func=pin_types.BIDIR),
            Pin(num='65',name='P65',func=pin_types.BIDIR),
            Pin(num='66',name='P66',func=pin_types.BIDIR),
            Pin(num='67',name='P67',func=pin_types.BIDIR),
            Pin(num='68',name='P68',func=pin_types.BIDIR),
            Pin(num='69',name='P69',func=pin_types.BIDIR),
            Pin(num='70',name='P70',func=pin_types.BIDIR),
            Pin(num='71',name='P71',func=pin_types.BIDIR),
            Pin(num='72',name='P72',func=pin_types.BIDIR),
            Pin(num='73',name='P73',func=pin_types.BIDIR),
            Pin(num='74',name='P74',func=pin_types.BIDIR),
            Pin(num='75',name='P75',func=pin_types.BIDIR),
            Pin(num='76',name='P76',func=pin_types.BIDIR),
            Pin(num='77',name='P77',func=pin_types.BIDIR),
            Pin(num='78',name='P78',func=pin_types.BIDIR),
            Pin(num='79',name='P79',func=pin_types.BIDIR),
            Pin(num='80',name='P80',func=pin_types.BIDIR),
            Pin(num='81',name='P81',func=pin_types.BIDIR),
            Pin(num='82',name='P82',func=pin_types.BIDIR),
            Pin(num='83',name='P83',func=pin_types.BIDIR),
            Pin(num='84',name='P84',func=pin_types.BIDIR),
            Pin(num='85',name='P85',func=pin_types.BIDIR),
            Pin(num='86',name='P86',func=pin_types.BIDIR),
            Pin(num='87',name='P87',func=pin_types.BIDIR),
            Pin(num='88',name='P88',func=pin_types.BIDIR),
            Pin(num='89',name='P89',func=pin_types.BIDIR),
            Pin(num='90',name='P90',func=pin_types.BIDIR),
            Pin(num='91',name='P91',func=pin_types.BIDIR),
            Pin(num='92',name='P92',func=pin_types.BIDIR),
            Pin(num='93',name='P93',func=pin_types.BIDIR),
            Pin(num='94',name='P94',func=pin_types.BIDIR),
            Pin(num='95',name='P95',func=pin_types.BIDIR),
            Pin(num='96',name='P96',func=pin_types.BIDIR),
            Pin(num='97',name='P97',func=pin_types.BIDIR),
            Pin(num='98',name='P98',func=pin_types.BIDIR),
            Pin(num='99',name='P99',func=pin_types.BIDIR),
            Pin(num='100',name='P100',func=pin_types.BIDIR),
            Pin(num='101',name='P101',func=pin_types.BIDIR),
            Pin(num='102',name='P102',func=pin_types.BIDIR),
            Pin(num='103',name='P103',func=pin_types.BIDIR),
            Pin(num='104',name='P104',func=pin_types.BIDIR),
            Pin(num='105',name='P105',func=pin_types.BIDIR),
            Pin(num='106',name='P106',func=pin_types.BIDIR),
            Pin(num='107',name='P107',func=pin_types.BIDIR),
            Pin(num='108',name='P108',func=pin_types.BIDIR),
            Pin(num='109',name='P109',func=pin_types.BIDIR),
            Pin(num='110',name='P110',func=pin_types.BIDIR),
            Pin(num='111',name='P111',func=pin_types.BIDIR),
            Pin(num='112',name='P112',func=pin_types.BIDIR),
            Pin(num='113',name='P113',func=pin_types.BIDIR),
            Pin(num='114',name='P114',func=pin_types.BIDIR),
            Pin(num='115',name='P115',func=pin_types.BIDIR),
            Pin(num='116',name='P116',func=pin_types.BIDIR),
            Pin(num='117',name='P117',func=pin_types.BIDIR),
            Pin(num='118',name='P118',func=pin_types.BIDIR),
            Pin(num='119',name='P119',func=pin_types.BIDIR),
            Pin(num='120',name='P120',func=pin_types.BIDIR),
            Pin(num='121',name='P121',func=pin_types.BIDIR),
            Pin(num='122',name='P122',func=pin_types.BIDIR),
            Pin(num='123',name='P123',func=pin_types.BIDIR),
            Pin(num='124',name='P124',func=pin_types.BIDIR),
            Pin(num='125',name='P125',func=pin_types.BIDIR),
            Pin(num='126',name='P126',func=pin_types.BIDIR),
            Pin(num='127',name='P127',func=pin_types.BIDIR),
            Pin(num='128',name='P128',func=pin_types.BIDIR),
            Pin(num='129',name='EP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'AMS1117-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-3.3'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'Package_TO_SOT_SMD:SOT-223-3_TabPin2'], 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':'linear regulator ldo fixed positive', 'description':'1A Low Dropout regulator, positive, 3.3V fixed output, SOT-223', 'datasheet':'http://www.advanced-monolithic.com/pdf/ds1117.pdf', 'pins':[
            Pin(num='3',name='VI',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VO',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AMS1117-2.5', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-2.5'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'Package_TO_SOT_SMD:SOT-223-3_TabPin2'], 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':'linear regulator ldo fixed positive', 'description':'1A Low Dropout regulator, positive, 2.5V fixed output, SOT-223', 'datasheet':'http://www.advanced-monolithic.com/pdf/ds1117.pdf', 'pins':[
            Pin(num='3',name='VI',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VO',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AZ1117-1.2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AZ1117-1.2'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':'Fixed Voltage Regulator 1A Positive LDO', 'description':'1A 20V Fixed LDO Linear Regulator, 1.2V, SOT-89/SOT-223/TO-220/TO-252/TO-263', 'datasheet':'https://www.diodes.com/assets/Datasheets/AZ1117.pdf', 'pins':[
            Pin(num='3',name='VI',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VO',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Crystal', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_HC49-4H_Vertical', 'keywords':'quartz ceramic resonator oscillator', 'description':'Two pin crystal', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_SMD:D_SOD-323', 'keywords':'diode', 'description':'Diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'HR911130C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'HR911130C'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'HANRUN_HR911130A', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE),
            Pin(num='3',name='P3',func=pin_types.PASSIVE),
            Pin(num='4',name='P4',func=pin_types.PASSIVE),
            Pin(num='5',name='P5',func=pin_types.PASSIVE),
            Pin(num='6',name='P6',func=pin_types.PASSIVE),
            Pin(num='7',name='P7',func=pin_types.PASSIVE),
            Pin(num='8',name='P8',func=pin_types.PASSIVE),
            Pin(num='9',name='P9',func=pin_types.PASSIVE),
            Pin(num='10',name='P10',func=pin_types.PASSIVE),
            Pin(num='11',name='P11',func=pin_types.PASSIVE),
            Pin(num='12',name='P12',func=pin_types.PASSIVE),
            Pin(num='13',name='P13',func=pin_types.PASSIVE),
            Pin(num='14',name='P14',func=pin_types.PASSIVE),
            Pin(num='S1',name='SH1',func=pin_types.PASSIVE),
            Pin(num='S2',name='SH2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'V3c', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'V3c'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'TODO:V3c_QFP', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='P_VCORE',name='VCC_CORE',func=pin_types.PWRIN),
            Pin(num='P_VIO',name='VCC_IO',func=pin_types.PWRIN),
            Pin(num='P_VDDR',name='VCC_DRAM',func=pin_types.PWRIN),
            Pin(num='P_GND',name='GND',func=pin_types.PWRIN),
            Pin(num='P_XI',name='XTAL_IN',func=pin_types.INPUT),
            Pin(num='P_XO',name='XTAL_OUT',func=pin_types.OUTPUT),
            Pin(num='P_RST',name='RESET_N',func=pin_types.INPUT),
            Pin(num='P_SCLK',name='SPI0_CLK',func=pin_types.OUTPUT),
            Pin(num='P_MOSI',name='SPI0_MOSI',func=pin_types.OUTPUT),
            Pin(num='P_MISO',name='SPI0_MISO',func=pin_types.INPUT),
            Pin(num='P_CS',name='SPI0_CS',func=pin_types.OUTPUT),
            Pin(num='P_FSCLK',name='SPI1_CLK',func=pin_types.OUTPUT),
            Pin(num='P_FMOSI',name='SPI1_MOSI',func=pin_types.OUTPUT),
            Pin(num='P_FMISO',name='SPI1_MISO',func=pin_types.INPUT),
            Pin(num='P_FCS',name='SPI1_CS',func=pin_types.OUTPUT),
            Pin(num='P_RTXD0',name='EMAC_TXD0',func=pin_types.OUTPUT),
            Pin(num='P_RTXD1',name='EMAC_TXD1',func=pin_types.OUTPUT),
            Pin(num='P_RTXEN',name='EMAC_TXEN',func=pin_types.OUTPUT),
            Pin(num='P_RRXD0',name='EMAC_RXD0',func=pin_types.INPUT),
            Pin(num='P_RRXD1',name='EMAC_RXD1',func=pin_types.INPUT),
            Pin(num='P_RCRS',name='EMAC_CRSDV',func=pin_types.INPUT),
            Pin(num='P_RCLK',name='EMAC_REFCLK',func=pin_types.INPUT),
            Pin(num='P_MDC',name='EMAC_MDC',func=pin_types.OUTPUT),
            Pin(num='P_MDIO',name='EMAC_MDIO',func=pin_types.BIDIR),
            Pin(num='P_UTX',name='UART0_TX',func=pin_types.OUTPUT),
            Pin(num='P_URX',name='UART0_RX',func=pin_types.INPUT),
            Pin(num='P_BOOT',name='BOOT_SEL',func=pin_types.INPUT)] }),
        Part(**{ 'name':'SPI_NAND', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SPI_NAND'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_5.23x5.23mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='CS_N',func=pin_types.INPUT),
            Pin(num='2',name='MISO',func=pin_types.OUTPUT),
            Pin(num='3',name='WP_N',func=pin_types.INPUT),
            Pin(num='4',name='GND',func=pin_types.PWRIN),
            Pin(num='5',name='MOSI',func=pin_types.INPUT),
            Pin(num='6',name='CLK',func=pin_types.INPUT),
            Pin(num='7',name='HOLD_N',func=pin_types.INPUT),
            Pin(num='8',name='VCC',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PASSIVE),
            Pin(num='2',name='TX',func=pin_types.PASSIVE),
            Pin(num='3',name='RX',func=pin_types.PASSIVE)] })])