from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

netlistscript = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'MSTB2,5/3-GF-5,08_1776511', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MSTB2,5/3-GF-5,08_1776511'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_Phoenix_MSTB:PhoenixContact_MSTB_2,5_3-GF-5,08_1x03_P5.08mm_Horizontal_ThreadedFlange', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='24V',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PASSIVE),
            Pin(num='3',name='PE',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Fuse_2A_TL', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Fuse_2A_TL'}), 'ref_prefix':'F', 'fplist':None, 'footprint':'Fuse:Fuse_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BSP315P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BSP315P'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='D',func=pin_types.PASSIVE),
            Pin(num='3',name='S',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BZX84C12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BZX84C12'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SMBJ30A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SMBJ30A'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SMB', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'MOV_S14K30_DNP', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MOV_S14K30_DNP'}), 'ref_prefix':'RV', 'fplist':None, 'footprint':'Varistor:RV_Disc_D9mm_W3.9mm_P5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BLM31PG601SN1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BLM31PG601SN1'}), 'ref_prefix':'FB', 'fplist':None, 'footprint':'Inductor_SMD:L_1206_3216Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'Capacitor_SMD:C_1210_3225Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LM5122', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM5122'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='DEMB',func=pin_types.INPUT),
            Pin(num='2',name='ILIM',func=pin_types.INPUT),
            Pin(num='3',name='AGND',func=pin_types.PWRIN),
            Pin(num='4',name='FB',func=pin_types.INPUT),
            Pin(num='5',name='COMP',func=pin_types.PASSIVE),
            Pin(num='6',name='RT',func=pin_types.PASSIVE),
            Pin(num='7',name='SS',func=pin_types.PASSIVE),
            Pin(num='8',name='SYNC',func=pin_types.INPUT),
            Pin(num='9',name='UVLO',func=pin_types.INPUT),
            Pin(num='10',name='VCC',func=pin_types.PWROUT),
            Pin(num='11',name='BST',func=pin_types.PASSIVE),
            Pin(num='12',name='HO',func=pin_types.OUTPUT),
            Pin(num='13',name='SW',func=pin_types.PASSIVE),
            Pin(num='14',name='LO',func=pin_types.OUTPUT),
            Pin(num='15',name='PGND',func=pin_types.PWRIN),
            Pin(num='16',name='CSP',func=pin_types.INPUT),
            Pin(num='17',name='EN',func=pin_types.INPUT),
            Pin(num='18',name='VIN',func=pin_types.PWRIN),
            Pin(num='19',name='PG',func=pin_types.OPENCOLL),
            Pin(num='20',name='CSN',func=pin_types.INPUT),
            Pin(num='21',name='EP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':None, 'footprint':'Inductor_SMD:L_1210_3225Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TPS54560', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS54560'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.29x3mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='BOOT',func=pin_types.PASSIVE),
            Pin(num='2',name='VIN',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='SS_TR',func=pin_types.PASSIVE),
            Pin(num='5',name='VSENSE',func=pin_types.INPUT),
            Pin(num='6',name='COMP',func=pin_types.PASSIVE),
            Pin(num='7',name='GND',func=pin_types.PWRIN),
            Pin(num='8',name='PH',func=pin_types.PWROUT),
            Pin(num='9',name='EP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SS54', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SS54'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SMA', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'AMS1117-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AMS1117-3.3'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='VO',func=pin_types.PWROUT),
            Pin(num='3',name='VI',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'AP2112K-2.5', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2112K-2.5'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT)] }),
        Part(**{ 'name':'AP2112K-1.2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2112K-1.2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT)] }),
        Part(**{ 'name':'TLV62569', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TLV62569'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='SW',func=pin_types.PWROUT),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='FB',func=pin_types.INPUT),
            Pin(num='5',name='VIN',func=pin_types.PWRIN),
            Pin(num='6',name='MODE',func=pin_types.INPUT)] }),
        Part(**{ 'name':'AP2112K-1.8', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2112K-1.8'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='EN',func=pin_types.INPUT),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT)] }),
        Part(**{ 'name':'KSZ9477S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'KSZ9477S'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'chips:QFP40P1600X1600X120-129N', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.BIDIR),
            Pin(num='2',name='P2',func=pin_types.BIDIR),
            Pin(num='3',name='P3',func=pin_types.BIDIR),
            Pin(num='4',name='P4',func=pin_types.BIDIR),
            Pin(num='5',name='P5',func=pin_types.BIDIR),
            Pin(num='6',name='P6',func=pin_types.BIDIR),
            Pin(num='7',name='P7',func=pin_types.BIDIR),
            Pin(num='8',name='P8',func=pin_types.BIDIR),
            Pin(num='9',name='P9',func=pin_types.BIDIR),
            Pin(num='10',name='P10',func=pin_types.BIDIR),
            Pin(num='11',name='P11',func=pin_types.BIDIR),
            Pin(num='12',name='P12',func=pin_types.BIDIR),
            Pin(num='13',name='P13',func=pin_types.BIDIR),
            Pin(num='14',name='P14',func=pin_types.BIDIR),
            Pin(num='15',name='P15',func=pin_types.BIDIR),
            Pin(num='16',name='P16',func=pin_types.BIDIR),
            Pin(num='17',name='P17',func=pin_types.BIDIR),
            Pin(num='18',name='P18',func=pin_types.BIDIR),
            Pin(num='19',name='P19',func=pin_types.BIDIR),
            Pin(num='20',name='P20',func=pin_types.BIDIR),
            Pin(num='21',name='P21',func=pin_types.BIDIR),
            Pin(num='22',name='P22',func=pin_types.BIDIR),
            Pin(num='23',name='P23',func=pin_types.BIDIR),
            Pin(num='24',name='P24',func=pin_types.BIDIR),
            Pin(num='25',name='P25',func=pin_types.BIDIR),
            Pin(num='26',name='P26',func=pin_types.BIDIR),
            Pin(num='27',name='P27',func=pin_types.BIDIR),
            Pin(num='28',name='P28',func=pin_types.BIDIR),
            Pin(num='29',name='P29',func=pin_types.BIDIR),
            Pin(num='30',name='P30',func=pin_types.BIDIR),
            Pin(num='31',name='P31',func=pin_types.BIDIR),
            Pin(num='32',name='P32',func=pin_types.BIDIR),
            Pin(num='33',name='P33',func=pin_types.BIDIR),
            Pin(num='34',name='P34',func=pin_types.BIDIR),
            Pin(num='35',name='P35',func=pin_types.BIDIR),
            Pin(num='36',name='P36',func=pin_types.BIDIR),
            Pin(num='37',name='P37',func=pin_types.BIDIR),
            Pin(num='38',name='P38',func=pin_types.BIDIR),
            Pin(num='39',name='P39',func=pin_types.BIDIR),
            Pin(num='40',name='P40',func=pin_types.BIDIR),
            Pin(num='41',name='P41',func=pin_types.BIDIR),
            Pin(num='42',name='P42',func=pin_types.BIDIR),
            Pin(num='43',name='P43',func=pin_types.BIDIR),
            Pin(num='44',name='P44',func=pin_types.BIDIR),
            Pin(num='45',name='P45',func=pin_types.BIDIR),
            Pin(num='46',name='P46',func=pin_types.BIDIR),
            Pin(num='47',name='P47',func=pin_types.BIDIR),
            Pin(num='48',name='P48',func=pin_types.BIDIR),
            Pin(num='49',name='P49',func=pin_types.BIDIR),
            Pin(num='50',name='P50',func=pin_types.BIDIR),
            Pin(num='51',name='P51',func=pin_types.BIDIR),
            Pin(num='52',name='P52',func=pin_types.BIDIR),
            Pin(num='53',name='P53',func=pin_types.BIDIR),
            Pin(num='54',name='P54',func=pin_types.BIDIR),
            Pin(num='55',name='P55',func=pin_types.BIDIR),
            Pin(num='56',name='P56',func=pin_types.BIDIR),
            Pin(num='57',name='P57',func=pin_types.BIDIR),
            Pin(num='58',name='P58',func=pin_types.BIDIR),
            Pin(num='59',name='P59',func=pin_types.BIDIR),
            Pin(num='60',name='P60',func=pin_types.BIDIR),
            Pin(num='61',name='P61',func=pin_types.BIDIR),
            Pin(num='62',name='P62',func=pin_types.BIDIR),
            Pin(num='63',name='P63',func=pin_types.BIDIR),
            Pin(num='64',name='P64',func=pin_types.BIDIR),
            Pin(num='65',name='P65',func=pin_types.BIDIR),
            Pin(num='66',name='P66',func=pin_types.BIDIR),
            Pin(num='67',name='P67',func=pin_types.BIDIR),
            Pin(num='68',name='P68',func=pin_types.BIDIR),
            Pin(num='69',name='P69',func=pin_types.BIDIR),
            Pin(num='70',name='P70',func=pin_types.BIDIR),
            Pin(num='71',name='P71',func=pin_types.BIDIR),
            Pin(num='72',name='P72',func=pin_types.BIDIR),
            Pin(num='73',name='P73',func=pin_types.BIDIR),
            Pin(num='74',name='P74',func=pin_types.BIDIR),
            Pin(num='75',name='P75',func=pin_types.BIDIR),
            Pin(num='76',name='P76',func=pin_types.BIDIR),
            Pin(num='77',name='P77',func=pin_types.BIDIR),
            Pin(num='78',name='P78',func=pin_types.BIDIR),
            Pin(num='79',name='P79',func=pin_types.BIDIR),
            Pin(num='80',name='P80',func=pin_types.BIDIR),
            Pin(num='81',name='P81',func=pin_types.BIDIR),
            Pin(num='82',name='P82',func=pin_types.BIDIR),
            Pin(num='83',name='P83',func=pin_types.BIDIR),
            Pin(num='84',name='P84',func=pin_types.BIDIR),
            Pin(num='85',name='P85',func=pin_types.BIDIR),
            Pin(num='86',name='P86',func=pin_types.BIDIR),
            Pin(num='87',name='P87',func=pin_types.BIDIR),
            Pin(num='88',name='P88',func=pin_types.BIDIR),
            Pin(num='89',name='P89',func=pin_types.BIDIR),
            Pin(num='90',name='P90',func=pin_types.BIDIR),
            Pin(num='91',name='P91',func=pin_types.BIDIR),
            Pin(num='92',name='P92',func=pin_types.BIDIR),
            Pin(num='93',name='P93',func=pin_types.BIDIR),
            Pin(num='94',name='P94',func=pin_types.BIDIR),
            Pin(num='95',name='P95',func=pin_types.BIDIR),
            Pin(num='96',name='P96',func=pin_types.BIDIR),
            Pin(num='97',name='P97',func=pin_types.BIDIR),
            Pin(num='98',name='P98',func=pin_types.BIDIR),
            Pin(num='99',name='P99',func=pin_types.BIDIR),
            Pin(num='100',name='P100',func=pin_types.BIDIR),
            Pin(num='101',name='P101',func=pin_types.BIDIR),
            Pin(num='102',name='P102',func=pin_types.BIDIR),
            Pin(num='103',name='P103',func=pin_types.BIDIR),
            Pin(num='104',name='P104',func=pin_types.BIDIR),
            Pin(num='105',name='P105',func=pin_types.BIDIR),
            Pin(num='106',name='P106',func=pin_types.BIDIR),
            Pin(num='107',name='P107',func=pin_types.BIDIR),
            Pin(num='108',name='P108',func=pin_types.BIDIR),
            Pin(num='109',name='P109',func=pin_types.BIDIR),
            Pin(num='110',name='P110',func=pin_types.BIDIR),
            Pin(num='111',name='P111',func=pin_types.BIDIR),
            Pin(num='112',name='P112',func=pin_types.BIDIR),
            Pin(num='113',name='P113',func=pin_types.BIDIR),
            Pin(num='114',name='P114',func=pin_types.BIDIR),
            Pin(num='115',name='P115',func=pin_types.BIDIR),
            Pin(num='116',name='P116',func=pin_types.BIDIR),
            Pin(num='117',name='P117',func=pin_types.BIDIR),
            Pin(num='118',name='P118',func=pin_types.BIDIR),
            Pin(num='119',name='P119',func=pin_types.BIDIR),
            Pin(num='120',name='P120',func=pin_types.BIDIR),
            Pin(num='121',name='P121',func=pin_types.BIDIR),
            Pin(num='122',name='P122',func=pin_types.BIDIR),
            Pin(num='123',name='P123',func=pin_types.BIDIR),
            Pin(num='124',name='P124',func=pin_types.BIDIR),
            Pin(num='125',name='P125',func=pin_types.BIDIR),
            Pin(num='126',name='P126',func=pin_types.BIDIR),
            Pin(num='127',name='P127',func=pin_types.BIDIR),
            Pin(num='128',name='P128',func=pin_types.BIDIR),
            Pin(num='129',name='EP',func=pin_types.PASSIVE),
            Pin(num='E_1',name='EP_1',func=pin_types.PASSIVE),
            Pin(num='E_2',name='EP_2',func=pin_types.PASSIVE),
            Pin(num='E_3',name='EP_3',func=pin_types.PASSIVE),
            Pin(num='E_4',name='EP_4',func=pin_types.PASSIVE),
            Pin(num='E_5',name='EP_5',func=pin_types.PASSIVE),
            Pin(num='E_6',name='EP_6',func=pin_types.PASSIVE),
            Pin(num='E_7',name='EP_7',func=pin_types.PASSIVE),
            Pin(num='E_8',name='EP_8',func=pin_types.PASSIVE),
            Pin(num='E_9',name='EP_9',func=pin_types.PASSIVE),
            Pin(num='E_10',name='EP_10',func=pin_types.PASSIVE),
            Pin(num='E_11',name='EP_11',func=pin_types.PASSIVE),
            Pin(num='E_12',name='EP_12',func=pin_types.PASSIVE),
            Pin(num='E_13',name='EP_13',func=pin_types.PASSIVE),
            Pin(num='E_14',name='EP_14',func=pin_types.PASSIVE),
            Pin(num='E_15',name='EP_15',func=pin_types.PASSIVE),
            Pin(num='E_16',name='EP_16',func=pin_types.PASSIVE),
            Pin(num='E_17',name='EP_17',func=pin_types.PASSIVE),
            Pin(num='E_18',name='EP_18',func=pin_types.PASSIVE),
            Pin(num='E_19',name='EP_19',func=pin_types.PASSIVE),
            Pin(num='E_20',name='EP_20',func=pin_types.PASSIVE),
            Pin(num='E_21',name='EP_21',func=pin_types.PASSIVE),
            Pin(num='E_22',name='EP_22',func=pin_types.PASSIVE),
            Pin(num='E_23',name='EP_23',func=pin_types.PASSIVE),
            Pin(num='E_24',name='EP_24',func=pin_types.PASSIVE),
            Pin(num='E_25',name='EP_25',func=pin_types.PASSIVE),
            Pin(num='E_26',name='EP_26',func=pin_types.PASSIVE),
            Pin(num='E_27',name='EP_27',func=pin_types.PASSIVE),
            Pin(num='E_28',name='EP_28',func=pin_types.PASSIVE),
            Pin(num='E_29',name='EP_29',func=pin_types.PASSIVE),
            Pin(num='E_30',name='EP_30',func=pin_types.PASSIVE),
            Pin(num='E_31',name='EP_31',func=pin_types.PASSIVE),
            Pin(num='E_32',name='EP_32',func=pin_types.PASSIVE),
            Pin(num='E_33',name='EP_33',func=pin_types.PASSIVE),
            Pin(num='E_34',name='EP_34',func=pin_types.PASSIVE),
            Pin(num='E_35',name='EP_35',func=pin_types.PASSIVE),
            Pin(num='E_36',name='EP_36',func=pin_types.PASSIVE),
            Pin(num='E_37',name='EP_37',func=pin_types.PASSIVE),
            Pin(num='E_38',name='EP_38',func=pin_types.PASSIVE),
            Pin(num='E_39',name='EP_39',func=pin_types.PASSIVE),
            Pin(num='E_40',name='EP_40',func=pin_types.PASSIVE),
            Pin(num='E_41',name='EP_41',func=pin_types.PASSIVE),
            Pin(num='E_42',name='EP_42',func=pin_types.PASSIVE),
            Pin(num='E_43',name='EP_43',func=pin_types.PASSIVE),
            Pin(num='E_44',name='EP_44',func=pin_types.PASSIVE),
            Pin(num='E_45',name='EP_45',func=pin_types.PASSIVE),
            Pin(num='E_46',name='EP_46',func=pin_types.PASSIVE),
            Pin(num='E_47',name='EP_47',func=pin_types.PASSIVE),
            Pin(num='E_48',name='EP_48',func=pin_types.PASSIVE),
            Pin(num='E_49',name='EP_49',func=pin_types.PASSIVE),
            Pin(num='E_50',name='EP_50',func=pin_types.PASSIVE),
            Pin(num='E_51',name='EP_51',func=pin_types.PASSIVE),
            Pin(num='E_52',name='EP_52',func=pin_types.PASSIVE),
            Pin(num='E_53',name='EP_53',func=pin_types.PASSIVE),
            Pin(num='E_54',name='EP_54',func=pin_types.PASSIVE),
            Pin(num='E_55',name='EP_55',func=pin_types.PASSIVE),
            Pin(num='E_56',name='EP_56',func=pin_types.PASSIVE),
            Pin(num='E_57',name='EP_57',func=pin_types.PASSIVE),
            Pin(num='E_58',name='EP_58',func=pin_types.PASSIVE),
            Pin(num='E_59',name='EP_59',func=pin_types.PASSIVE),
            Pin(num='E_60',name='EP_60',func=pin_types.PASSIVE),
            Pin(num='E_61',name='EP_61',func=pin_types.PASSIVE),
            Pin(num='E_62',name='EP_62',func=pin_types.PASSIVE),
            Pin(num='E_63',name='EP_63',func=pin_types.PASSIVE),
            Pin(num='E_64',name='EP_64',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Crystal_25MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal_25MHz'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_2016-4Pin_2.0x1.6mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'D_1N4148', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_1N4148'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-323', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE),
            Pin(num='2',name='A',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LPJG0926HENL', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LPJG0926HENL'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'connectors:LPJG0926HENL', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE),
            Pin(num='3',name='P3',func=pin_types.PASSIVE),
            Pin(num='4',name='P4',func=pin_types.PASSIVE),
            Pin(num='5',name='P5',func=pin_types.PASSIVE),
            Pin(num='6',name='P6',func=pin_types.PASSIVE),
            Pin(num='7',name='P7',func=pin_types.PASSIVE),
            Pin(num='8',name='P8',func=pin_types.PASSIVE),
            Pin(num='9',name='P9',func=pin_types.PASSIVE),
            Pin(num='10',name='P10',func=pin_types.PASSIVE),
            Pin(num='11',name='P11',func=pin_types.PASSIVE),
            Pin(num='12',name='P12',func=pin_types.PASSIVE),
            Pin(num='13',name='P13',func=pin_types.PASSIVE),
            Pin(num='14',name='P14',func=pin_types.PASSIVE),
            Pin(num='15',name='P15',func=pin_types.PASSIVE),
            Pin(num='16',name='P16',func=pin_types.PASSIVE),
            Pin(num='17',name='P17',func=pin_types.PASSIVE),
            Pin(num='18',name='P18',func=pin_types.PASSIVE),
            Pin(num='S1',name='SH1',func=pin_types.PASSIVE),
            Pin(num='S2',name='SH2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TPS23861', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS23861'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:TSSOP-28_4.4x9.7mm_P0.65mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN),
            Pin(num='2',name='RESET',func=pin_types.INPUT),
            Pin(num='3',name='SCL',func=pin_types.INPUT),
            Pin(num='4',name='SDAI',func=pin_types.INPUT),
            Pin(num='5',name='SDAO',func=pin_types.OPENCOLL),
            Pin(num='6',name='INT',func=pin_types.OPENCOLL),
            Pin(num='7',name='DGND',func=pin_types.PWRIN),
            Pin(num='8',name='SEN3',func=pin_types.INPUT),
            Pin(num='9',name='DRAIN3',func=pin_types.INPUT),
            Pin(num='10',name='GATE3',func=pin_types.OUTPUT),
            Pin(num='11',name='KSENSB',func=pin_types.INPUT),
            Pin(num='12',name='SEN4',func=pin_types.INPUT),
            Pin(num='13',name='DRAIN4',func=pin_types.INPUT),
            Pin(num='14',name='GATE4',func=pin_types.OUTPUT),
            Pin(num='15',name='SEN1',func=pin_types.INPUT),
            Pin(num='16',name='DRAIN1',func=pin_types.INPUT),
            Pin(num='17',name='GATE1',func=pin_types.OUTPUT),
            Pin(num='18',name='KSENSA',func=pin_types.INPUT),
            Pin(num='19',name='SEN2',func=pin_types.INPUT),
            Pin(num='20',name='DRAIN2',func=pin_types.INPUT),
            Pin(num='21',name='GATE2',func=pin_types.OUTPUT),
            Pin(num='22',name='AGND',func=pin_types.PWRIN),
            Pin(num='23',name='A3',func=pin_types.INPUT),
            Pin(num='24',name='SHTDWN',func=pin_types.INPUT),
            Pin(num='25',name='AIN',func=pin_types.INPUT),
            Pin(num='26',name='AOUT',func=pin_types.OUTPUT),
            Pin(num='27',name='NC',func=pin_types.NOCONNECT),
            Pin(num='28',name='VPWR',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'NMOS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NMOS'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='D',func=pin_types.PASSIVE),
            Pin(num='3',name='S',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'T113-S3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'T113-S3'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'chips:eLQFP-128-1EP_14x14mm_P0.4mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='86',name='PB2',func=pin_types.BIDIR),
            Pin(num='85',name='PB3',func=pin_types.BIDIR),
            Pin(num='84',name='PB4',func=pin_types.BIDIR),
            Pin(num='82',name='PB5',func=pin_types.BIDIR),
            Pin(num='80',name='PB6',func=pin_types.BIDIR),
            Pin(num='79',name='PB7',func=pin_types.BIDIR),
            Pin(num='19',name='PC2',func=pin_types.BIDIR),
            Pin(num='18',name='PC3',func=pin_types.BIDIR),
            Pin(num='17',name='PC4',func=pin_types.BIDIR),
            Pin(num='16',name='PC5',func=pin_types.BIDIR),
            Pin(num='15',name='PC6',func=pin_types.BIDIR),
            Pin(num='14',name='PC7',func=pin_types.BIDIR),
            Pin(num='55',name='PD0',func=pin_types.BIDIR),
            Pin(num='56',name='PD1',func=pin_types.BIDIR),
            Pin(num='57',name='PD2',func=pin_types.BIDIR),
            Pin(num='58',name='PD3',func=pin_types.BIDIR),
            Pin(num='59',name='PD4',func=pin_types.BIDIR),
            Pin(num='60',name='PD5',func=pin_types.BIDIR),
            Pin(num='61',name='PD6',func=pin_types.BIDIR),
            Pin(num='62',name='PD7',func=pin_types.BIDIR),
            Pin(num='63',name='PD8',func=pin_types.BIDIR),
            Pin(num='64',name='PD9',func=pin_types.BIDIR),
            Pin(num='67',name='PD10',func=pin_types.BIDIR),
            Pin(num='68',name='PD11',func=pin_types.BIDIR),
            Pin(num='70',name='PD12',func=pin_types.BIDIR),
            Pin(num='69',name='PD13',func=pin_types.BIDIR),
            Pin(num='71',name='PD14',func=pin_types.BIDIR),
            Pin(num='72',name='PD15',func=pin_types.BIDIR),
            Pin(num='73',name='PD16',func=pin_types.BIDIR),
            Pin(num='74',name='PD17',func=pin_types.BIDIR),
            Pin(num='75',name='PD18',func=pin_types.BIDIR),
            Pin(num='76',name='PD19',func=pin_types.BIDIR),
            Pin(num='54',name='PD20',func=pin_types.BIDIR),
            Pin(num='53',name='PD21',func=pin_types.BIDIR),
            Pin(num='52',name='PD22',func=pin_types.BIDIR),
            Pin(num='65',name='VCC-LVDS',func=pin_types.PWRIN),
            Pin(num='66',name='VCC-PD',func=pin_types.PWRIN),
            Pin(num='44',name='PE0',func=pin_types.BIDIR),
            Pin(num='45',name='PE1',func=pin_types.BIDIR),
            Pin(num='35',name='PE2',func=pin_types.BIDIR),
            Pin(num='33',name='PE3',func=pin_types.BIDIR),
            Pin(num='43',name='PE4',func=pin_types.BIDIR),
            Pin(num='42',name='PE5',func=pin_types.BIDIR),
            Pin(num='41',name='PE6',func=pin_types.BIDIR),
            Pin(num='40',name='PE7',func=pin_types.BIDIR),
            Pin(num='39',name='PE8',func=pin_types.BIDIR),
            Pin(num='38',name='PE9',func=pin_types.BIDIR),
            Pin(num='37',name='PE10',func=pin_types.BIDIR),
            Pin(num='36',name='PE11',func=pin_types.BIDIR),
            Pin(num='32',name='PE12',func=pin_types.BIDIR),
            Pin(num='31',name='PE13',func=pin_types.BIDIR),
            Pin(num='34',name='VCC-PE',func=pin_types.PWRIN),
            Pin(num='7',name='PF0',func=pin_types.BIDIR),
            Pin(num='8',name='PF1',func=pin_types.BIDIR),
            Pin(num='9',name='PF2',func=pin_types.BIDIR),
            Pin(num='10',name='PF3',func=pin_types.BIDIR),
            Pin(num='11',name='PF4',func=pin_types.BIDIR),
            Pin(num='12',name='PF5',func=pin_types.BIDIR),
            Pin(num='13',name='PF6',func=pin_types.BIDIR),
            Pin(num='120',name='PG0',func=pin_types.BIDIR),
            Pin(num='118',name='PG1',func=pin_types.BIDIR),
            Pin(num='119',name='PG2',func=pin_types.BIDIR),
            Pin(num='121',name='PG3',func=pin_types.BIDIR),
            Pin(num='123',name='PG4',func=pin_types.BIDIR),
            Pin(num='122',name='PG5',func=pin_types.BIDIR),
            Pin(num='1',name='PG6',func=pin_types.BIDIR),
            Pin(num='2',name='PG7',func=pin_types.BIDIR),
            Pin(num='3',name='PG8',func=pin_types.BIDIR),
            Pin(num='4',name='PG9',func=pin_types.BIDIR),
            Pin(num='5',name='PG10',func=pin_types.BIDIR),
            Pin(num='6',name='PG11',func=pin_types.BIDIR),
            Pin(num='124',name='PG12',func=pin_types.BIDIR),
            Pin(num='125',name='PG13',func=pin_types.BIDIR),
            Pin(num='126',name='PG14',func=pin_types.BIDIR),
            Pin(num='127',name='PG15',func=pin_types.BIDIR),
            Pin(num='128',name='VCC-PG',func=pin_types.PWRIN),
            Pin(num='47',name='DZQ',func=pin_types.BIDIR),
            Pin(num='48',name='VCC-DRAM0',func=pin_types.PWRIN),
            Pin(num='49',name='VCC-DRAM1',func=pin_types.PWRIN),
            Pin(num='50',name='VDD18-DRAM',func=pin_types.PWRIN),
            Pin(num='27',name='RESET',func=pin_types.BIDIR),
            Pin(num='101',name='GPADC0',func=pin_types.BIDIR),
            Pin(num='102',name='TP-X1',func=pin_types.BIDIR),
            Pin(num='103',name='TP-X2',func=pin_types.BIDIR),
            Pin(num='104',name='TP-Y1',func=pin_types.BIDIR),
            Pin(num='105',name='TP-Y2',func=pin_types.BIDIR),
            Pin(num='114',name='USB0-DM',func=pin_types.BIDIR),
            Pin(num='115',name='USB0-DP',func=pin_types.BIDIR),
            Pin(num='113',name='USB1-DM',func=pin_types.BIDIR),
            Pin(num='112',name='USB1-DP',func=pin_types.BIDIR),
            Pin(num='78',name='TVOUT0',func=pin_types.BIDIR),
            Pin(num='77',name='VCC-TVOUT',func=pin_types.PWRIN),
            Pin(num='108',name='TVIN0',func=pin_types.BIDIR),
            Pin(num='109',name='TVIN1',func=pin_types.BIDIR),
            Pin(num='110',name='TVIN-VRP',func=pin_types.BIDIR),
            Pin(num='111',name='TVIN-VRN',func=pin_types.BIDIR),
            Pin(num='107',name='VCC-TVIN',func=pin_types.PWRIN),
            Pin(num='87',name='MICIN3P',func=pin_types.BIDIR),
            Pin(num='88',name='MICIN3N',func=pin_types.BIDIR),
            Pin(num='93',name='FMINR',func=pin_types.BIDIR),
            Pin(num='94',name='FMINL',func=pin_types.BIDIR),
            Pin(num='95',name='LINEINR',func=pin_types.BIDIR),
            Pin(num='96',name='LINEINL',func=pin_types.BIDIR),
            Pin(num='98',name='HPOUTR',func=pin_types.BIDIR),
            Pin(num='99',name='HPOUTL',func=pin_types.BIDIR),
            Pin(num='100',name='HPOUTFB',func=pin_types.BIDIR),
            Pin(num='97',name='HPVCC',func=pin_types.PWRIN),
            Pin(num='92',name='VRA1',func=pin_types.BIDIR),
            Pin(num='90',name='VRA2',func=pin_types.BIDIR),
            Pin(num='89',name='AVCC',func=pin_types.PWRIN),
            Pin(num='91',name='AGND',func=pin_types.PWRIN),
            Pin(num='25',name='X32KIN',func=pin_types.BIDIR),
            Pin(num='24',name='X32KOUT',func=pin_types.BIDIR),
            Pin(num='26',name='VCC-RTC',func=pin_types.PWRIN),
            Pin(num='20',name='VCC-PLL',func=pin_types.PWRIN),
            Pin(num='23',name='DXIN',func=pin_types.BIDIR),
            Pin(num='22',name='DXOUT',func=pin_types.BIDIR),
            Pin(num='21',name='REFCLK-OUT',func=pin_types.BIDIR),
            Pin(num='106',name='NC0',func=pin_types.NOCONNECT),
            Pin(num='29',name='LDO-IN',func=pin_types.PWRIN),
            Pin(num='28',name='LDOA-OUT',func=pin_types.PWRIN),
            Pin(num='30',name='LDOB-OUT',func=pin_types.PWRIN),
            Pin(num='83',name='VCC-IO',func=pin_types.PWRIN),
            Pin(num='46',name='VDD-SYS0',func=pin_types.PWRIN),
            Pin(num='51',name='VDD-SYS1',func=pin_types.PWRIN),
            Pin(num='81',name='VDD-SYS2',func=pin_types.PWRIN),
            Pin(num='116',name='VDD-CORE0',func=pin_types.PWRIN),
            Pin(num='117',name='VDD-CORE1',func=pin_types.PWRIN),
            Pin(num='129',name='EP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Crystal_24MHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal_24MHz'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_2016-4Pin_2.0x1.6mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Crystal_32K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal_32K'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_3215-2Pin_3.2x1.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='TX',func=pin_types.PASSIVE),
            Pin(num='2',name='RX',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'microSD', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'microSD'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_Card:microSD_HC_Molex_104031-0811', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P1',func=pin_types.PASSIVE),
            Pin(num='2',name='P2',func=pin_types.PASSIVE),
            Pin(num='3',name='P3',func=pin_types.PASSIVE),
            Pin(num='4',name='P4',func=pin_types.PASSIVE),
            Pin(num='5',name='P5',func=pin_types.PASSIVE),
            Pin(num='6',name='P6',func=pin_types.PASSIVE),
            Pin(num='7',name='P7',func=pin_types.PASSIVE),
            Pin(num='8',name='P8',func=pin_types.PASSIVE),
            Pin(num='9',name='P9',func=pin_types.PASSIVE),
            Pin(num='10',name='P10',func=pin_types.PASSIVE),
            Pin(num='11',name='P11',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'W25N02JWZEIF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W25N02JWZEIF'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='CS',func=pin_types.INPUT),
            Pin(num='2',name='DO',func=pin_types.OUTPUT),
            Pin(num='3',name='WP',func=pin_types.INPUT),
            Pin(num='4',name='GND',func=pin_types.PWRIN),
            Pin(num='5',name='DI',func=pin_types.INPUT),
            Pin(num='6',name='CLK',func=pin_types.INPUT),
            Pin(num='7',name='HOLD',func=pin_types.INPUT),
            Pin(num='8',name='VCC',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TPS3823', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS3823'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='RST',func=pin_types.OUTPUT),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='MR',func=pin_types.INPUT),
            Pin(num='4',name='VDD',func=pin_types.PWRIN),
            Pin(num='5',name='WDI',func=pin_types.INPUT)] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'Button_Switch_SMD:SW_Push_1P1T_NO_CK_KMR2', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='B',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'USB-C_2171820001', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB-C_2171820001'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'connectors:CONN_2171820001_MOL', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PWRIN),
            Pin(num='A4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='A7',name='DN1',func=pin_types.BIDIR),
            Pin(num='A9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A12',name='GND',func=pin_types.PWRIN),
            Pin(num='B1',name='GND',func=pin_types.PWRIN),
            Pin(num='B4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='B7',name='DN2',func=pin_types.BIDIR),
            Pin(num='B9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B12',name='GND',func=pin_types.PWRIN),
            Pin(num='S1',name='SHLD',func=pin_types.PASSIVE),
            Pin(num='S2',name='SHLD',func=pin_types.PASSIVE),
            Pin(num='S3',name='SHLD',func=pin_types.PASSIVE),
            Pin(num='S4',name='SHLD',func=pin_types.PASSIVE),
            Pin(num='MNT2',name='MNT',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='K',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TPS7B6933QDCYRQ1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS7B6933QDCYRQ1'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-223-3_TabPin2', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='VO',func=pin_types.PWROUT),
            Pin(num='3',name='VI',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'STM32G071CBTx', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32G071CBTx'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_QFP:LQFP-48_7x7mm_P0.5mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='4',name='VBAT',func=pin_types.PWRIN),
            Pin(num='5',name='VREF+',func=pin_types.PWRIN),
            Pin(num='6',name='VDD',func=pin_types.PWRIN),
            Pin(num='7',name='VSS',func=pin_types.PWRIN),
            Pin(num='10',name='NRST',func=pin_types.INPUT),
            Pin(num='13',name='PA2',func=pin_types.OUTPUT),
            Pin(num='14',name='PA3',func=pin_types.INPUT),
            Pin(num='15',name='PA4',func=pin_types.OPENCOLL),
            Pin(num='16',name='PA5',func=pin_types.INPUT),
            Pin(num='17',name='PA6',func=pin_types.OUTPUT),
            Pin(num='19',name='PB0',func=pin_types.INPUT),
            Pin(num='20',name='PB1',func=pin_types.OUTPUT),
            Pin(num='21',name='PB2',func=pin_types.OPENCOLL),
            Pin(num='42',name='PB3',func=pin_types.OPENCOLL),
            Pin(num='11',name='PA0',func=pin_types.OUTPUT),
            Pin(num='12',name='PA1',func=pin_types.INPUT),
            Pin(num='28',name='PA8',func=pin_types.BIDIR),
            Pin(num='35',name='PA13',func=pin_types.BIDIR),
            Pin(num='36',name='PA14',func=pin_types.BIDIR),
            Pin(num='45',name='PB6',func=pin_types.BIDIR),
            Pin(num='46',name='PB7',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'BAT54', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BAT54'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-323', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SWD_2x3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SWD_2x3'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_PinHeader_1.27mm:PinHeader_2x03_P1.27mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PASSIVE),
            Pin(num='2',name='SWDIO',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PASSIVE),
            Pin(num='4',name='SWCLK',func=pin_types.PASSIVE),
            Pin(num='5',name='NRST',func=pin_types.PASSIVE),
            Pin(num='6',name='NC',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'DS18B20', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DS18B20'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_THT:TO-92_Inline', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='DQ',func=pin_types.BIDIR),
            Pin(num='3',name='VDD',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'SHT40-AD1B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SHT40-AD1B'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Sensor_Humidity:Sensirion_DFN-4_1.5x1.5mm_P0.8mm_SHT4x_NoCentralPad', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='SDA',func=pin_types.BIDIR),
            Pin(num='2',name='SCL',func=pin_types.INPUT),
            Pin(num='3',name='VDD',func=pin_types.PWRIN),
            Pin(num='4',name='VSS',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Thermostat_NO_95C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Thermostat_NO_95C'}), 'ref_prefix':'TS', 'fplist':None, 'footprint':'Connector_Wire:SolderWire-0.25sqmm_1x02_P4.2mm_D0.65mm_OD1.7mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'HFD23-024-1ZS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'HFD23-024-1ZS'}), 'ref_prefix':'K', 'fplist':None, 'footprint':'connectors:Relay_HFD23_1C_THT', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='NO',func=pin_types.PASSIVE),
            Pin(num='2',name='A2',func=pin_types.PASSIVE),
            Pin(num='3',name='COM',func=pin_types.PASSIVE),
            Pin(num='4',name='NC',func=pin_types.PASSIVE),
            Pin(num='5',name='A1',func=pin_types.PASSIVE),
            Pin(num='6',name='COM',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'1N4148W', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'1N4148W'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-123', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'2N7002', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2N7002'}), 'ref_prefix':'Q', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='S',func=pin_types.PASSIVE),
            Pin(num='3',name='D',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'MC1,5/5-GF-3,5_1843826', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MC1,5/5-GF-3,5_1843826'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_Phoenix_MC:PhoenixContact_MC_1,5_5-GF-3.5_1x05_P3.50mm_Horizontal_ThreadedFlange', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='COM',func=pin_types.PASSIVE),
            Pin(num='2',name='NO',func=pin_types.PASSIVE),
            Pin(num='3',name='NC',func=pin_types.PASSIVE),
            Pin(num='4',name='DI+',func=pin_types.PASSIVE),
            Pin(num='5',name='DI-',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SMBJ33CA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SMBJ33CA'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SMB', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'EL357N', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'EL357N'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOP-4_3.8x4.1mm_P2.54mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE),
            Pin(num='2',name='K',func=pin_types.PASSIVE),
            Pin(num='3',name='E',func=pin_types.PASSIVE),
            Pin(num='4',name='C',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'MountingHole_M3_PE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MountingHole_M3_PE'}), 'ref_prefix':'MH', 'fplist':None, 'footprint':'MountingHole:MountingHole_3mm_Pad', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE)] })])